-- Districts Table
CREATE TABLE IF NOT EXISTS districts (
  id INT PRIMARY KEY AUTO_INCREMENT,
  district_code VARCHAR(50) UNIQUE NOT NULL,
  district_name VARCHAR(100) NOT NULL,
  state VARCHAR(100),
  postal_code VARCHAR(20),
  zone_region VARCHAR(100),
  active_status VARCHAR(20) DEFAULT 'Active',
  remarks TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_district_code (district_code),
  INDEX idx_district_name (district_name),
  INDEX idx_state (state),
  INDEX idx_postal_code (postal_code)
);

-- Users Table
CREATE TABLE IF NOT EXISTS users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  full_name VARCHAR(100),
  role VARCHAR(20) DEFAULT 'user',
  district_id INT,
  active_status VARCHAR(20) DEFAULT 'Active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (district_id) REFERENCES districts(id) ON DELETE SET NULL,
  INDEX idx_username (username),
  INDEX idx_email (email),
  INDEX idx_district_id (district_id)
);

-- Ledgers Table (Customer/Party Master)
CREATE TABLE IF NOT EXISTS ledgers (
  id INT PRIMARY KEY AUTO_INCREMENT,
  party_code VARCHAR(50) UNIQUE NOT NULL,
  party_name VARCHAR(100) NOT NULL,
  party_type VARCHAR(50),
  address TEXT,
  district_id INT,
  state VARCHAR(100),
  gstin VARCHAR(20),
  pan VARCHAR(20),
  contact_person VARCHAR(100),
  mobile_number VARCHAR(20),
  email VARCHAR(100),
  ledger_mapping VARCHAR(100),
  active_status VARCHAR(20) DEFAULT 'Active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (district_id) REFERENCES districts(id) ON DELETE SET NULL,
  INDEX idx_party_code (party_code),
  INDEX idx_party_name (party_name),
  INDEX idx_district_id (district_id),
  INDEX idx_gstin (gstin)
);

-- Items Table (Product Master)
CREATE TABLE IF NOT EXISTS items (
  id INT PRIMARY KEY AUTO_INCREMENT,
  item_code VARCHAR(50) UNIQUE NOT NULL,
  item_name VARCHAR(100) NOT NULL,
  item_category VARCHAR(50),
  stock_group VARCHAR(50),
  unit_of_measure VARCHAR(20),
  hsn_code VARCHAR(20),
  gst_rate DECIMAL(5,2),
  cgst_rate DECIMAL(5,2),
  sgst_rate DECIMAL(5,2),
  igst_rate DECIMAL(5,2),
  item_type VARCHAR(20),
  opening_quantity DECIMAL(10,2),
  opening_value DECIMAL(10,2),
  minimum_stock_level DECIMAL(10,2),
  stock_quantity DECIMAL(10,2) DEFAULT 0,
  active_status VARCHAR(20) DEFAULT 'Active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_item_code (item_code),
  INDEX idx_item_name (item_name),
  INDEX idx_hsn_code (hsn_code)
);

-- Orders Table
CREATE TABLE IF NOT EXISTS orders (
  id INT PRIMARY KEY AUTO_INCREMENT,
  order_number VARCHAR(50) UNIQUE NOT NULL,
  ledger_id INT,
  item_id INT,
  quantity INT,
  unit_price DECIMAL(10,2),
  total_amount DECIMAL(10,2),
  order_date DATE,
  delivery_date DATE,
  status VARCHAR(20) DEFAULT 'Pending',
  payment_method VARCHAR(50) DEFAULT 'Pending',
  payment_status VARCHAR(20) DEFAULT 'Unpaid',
  paid_amount DECIMAL(10,2) DEFAULT 0,
  balance_due DECIMAL(10,2) DEFAULT 0,
  remarks TEXT,
  created_by INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (ledger_id) REFERENCES ledgers(id) ON DELETE SET NULL,
  FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_order_number (order_number),
  INDEX idx_status (status),
  INDEX idx_order_date (order_date),
  INDEX idx_payment_status (payment_status)
);

-- Order Items Table
CREATE TABLE IF NOT EXISTS order_items (
  id INT PRIMARY KEY AUTO_INCREMENT,
  order_id INT NOT NULL,
  item_id INT NOT NULL,
  qty_mt DECIMAL(10,3) DEFAULT 0,
  qty_pcs INT DEFAULT 0,
  rate DECIMAL(10,2) DEFAULT 0,
  amount DECIMAL(10,2) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
  INDEX idx_order_id (order_id),
  INDEX idx_item_id (item_id)
);

-- Insert Default Admin User (Password: admin123)
-- Note: The password hash below matches 'admin123' generated by bcrypt
INSERT INTO users (username, password, email, full_name, role, active_status)
VALUES ('admin', '$2b$10$Z3PD3vn/OG5PrtJ983IxvOq7FTXqwJzZLRKHiH.iNbNAZiom/okEa', 'admin@abs.com', 'System Administrator', 'admin', 'Active')
ON DUPLICATE KEY UPDATE active_status='Active';
